default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args:
          - --prose-wrap=always
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--preview]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
        files: ^(.*/)?pyproject.toml$
      - id: poetry-export
        name: poetry-export (prod)
        args:
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.txt"
      - id: poetry-export
        name: poetry-export (dev)
        args:
          - "--with"
          - "dev"
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.dev.txt"
